'use client';
import {useEffect,useMemo,useState} from 'react';
import Papa from 'papaparse';
import {jsPDF} from 'jspdf';

type QType='choice'|'ox'|'fill'|'essay';
type Question={id:string;type:QType;question:string;options:string[];answer:string;explanation:string;modelAnswer:string;rubric:string};
type Subject={id:string;name:string;color:string;source?:{url:string;mode:'sync'|'copy'};questions:Question[]};
type Attempt={id:string;subjectId:string;date:string;score:number;total:number;answers:{questionId:string;answer:string;correct:boolean|null}[]};
type PendingImport={name:string;url:string};
const SUBJECTS='study_subjects_v2',ATTEMPTS='study_attempts_v2';
const uid=()=>crypto.randomUUID();
const blankQ=():Question=>({id:uid(),type:'choice',question:'',options:['','','',''],answer:'',explanation:'',modelAnswer:'',rubric:''});
const typeName:Record<QType,string>={choice:'4択',ox:'○×',fill:'穴埋め',essay:'論述'};

function rowToQuestion(r:Record<string,string>):Question|null{
 const question=(r.question||r.問題文||'').trim(); if(!question)return null;
 const raw=(r.type||r.形式||'choice').toLowerCase();
 const type:QType=raw==='ox'||raw==='○×'?'ox':raw==='fill'||raw==='穴埋め'?'fill':raw==='essay'||raw==='論述'?'essay':'choice';
 return {id:uid(),type,question,options:[r.option1,r.option2,r.option3,r.option4].filter(Boolean),answer:r.answer||r.正解||'',explanation:r.explanation||r.解説||'',modelAnswer:r.modelAnswer||r.模範解答||'',rubric:r.rubric||r.採点ポイント||''};
}
async function loadSheet(url:string){return new Promise<Question[]>((resolve,reject)=>Papa.parse<Record<string,string>>(url,{download:true,header:true,skipEmptyLines:true,complete:r=>resolve(r.data.map(rowToQuestion).filter((q):q is Question=>!!q)),error:reject}));}

export default function Home(){
 const [ready,setReady]=useState(false),[subjects,setSubjects]=useState<Subject[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]);
 const [view,setView]=useState<'home'|'subject'|'manage'|'play'|'result'>('home'),[selected,setSelected]=useState('');
 const [editing,setEditing]=useState<Question|null>(null),[active,setActive]=useState<Question[]>([]),[index,setIndex]=useState(0),[draft,setDraft]=useState(''),[answers,setAnswers]=useState<Attempt['answers']>([]),[feedback,setFeedback]=useState<boolean|null>(null),[submitted,setSubmitted]=useState(false);
 const [pendingImport,setPendingImport]=useState<PendingImport|null>(null);
 const [subjectSettings,setSubjectSettings]=useState<Subject|null>(null),[settingsLoading,setSettingsLoading]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setSubjects(JSON.parse(localStorage.getItem(SUBJECTS)||'[]'));setAttempts(JSON.parse(localStorage.getItem(ATTEMPTS)||'[]'))}catch{}setReady(true)},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(SUBJECTS,JSON.stringify(subjects))},[subjects,ready]);
 useEffect(()=>{if(ready)localStorage.setItem(ATTEMPTS,JSON.stringify(attempts))},[attempts,ready]);
 const subject=subjects.find(s=>s.id===selected);
 const stats=useMemo(()=>attempts.filter(a=>a.subjectId===selected),[attempts,selected]);
 const saveSubject=(s:Subject)=>setSubjects(v=>v.some(x=>x.id===s.id)?v.map(x=>x.id===s.id?s:x):[...v,s]);
 function deleteSubject(){if(!subject)return;if(!confirm(`「${subject.name}」を削除しますか？\n問題と成績履歴もこの端末から削除されます。`))return;setSubjects(v=>v.filter(s=>s.id!==subject.id));setAttempts(v=>v.filter(a=>a.subjectId!==subject.id));setSelected('');setView('home')}
 async function addSubject(){const name=prompt('科目名を入力してください');if(!name)return;const url=prompt('スプレッドシートURL（後から設定する場合は空欄）')||'';if(url){setPendingImport({name,url});return}const s={id:uid(),name,color:'#3167e3',questions:[]};saveSubject(s);setSelected(s.id);setView('subject')}
 async function finishImport(mode:'sync'|'copy'){if(!pendingImport)return;try{const questions=await loadSheet(pendingImport.url);const s:Subject={id:uid(),name:pendingImport.name,color:'#3167e3',source:{url:pendingImport.url,mode},questions};saveSubject(s);setSelected(s.id);setView('subject');setPendingImport(null)}catch{alert('シートを読み込めませんでした。公開CSV URLを確認してください。')}}
 async function reloadSettings(){if(!subjectSettings?.source?.url)return alert('CSV URLを入力してください');setSettingsLoading(true);try{const questions=await loadSheet(subjectSettings.source.url);setSubjectSettings({...subjectSettings,questions});alert(`${questions.length}問を読み込みました`)}catch{alert('シートを読み込めませんでした。公開CSV URLを確認してください。')}finally{setSettingsLoading(false)}}
 async function saveSettings(){if(!subjectSettings?.name.trim())return alert('科目名を入力してください');let next=subjectSettings;if(subjectSettings.source?.url){setSettingsLoading(true);try{next={...subjectSettings,questions:await loadSheet(subjectSettings.source.url)}}catch{setSettingsLoading(false);return alert('CSVを読み込めませんでした。URLを確認してください。')}setSettingsLoading(false)}else{const {source:_,...withoutSource}=subjectSettings;void _;next=withoutSource}saveSubject(next);setSubjectSettings(null)}
 async function openSubject(s:Subject){let next=s;if(s.source?.mode==='sync'){try{next={...s,questions:await loadSheet(s.source.url)};saveSubject(next)}catch{alert('同期に失敗したため、保存済みデータを表示します')}}setSelected(s.id);setView('subject')}
 function saveQuestion(){if(!subject||!editing?.question.trim())return alert('問題文を入力してください');saveSubject({...subject,questions:subject.questions.some(q=>q.id===editing.id)?subject.questions.map(q=>q.id===editing.id?editing:q):[...subject.questions,editing]});setEditing(null)}
 function start(){if(!subject?.questions.length)return alert('問題を追加してください');setActive([...subject.questions].sort(()=>Math.random()-.5));setIndex(0);setAnswers([]);setDraft('');setFeedback(null);setSubmitted(false);setView('play')}
 function submit(){const q=active[index];let correct:boolean|null=null;if(q.type!=='essay')correct=draft.trim().toLowerCase()===q.answer.trim().toLowerCase();setFeedback(correct);setSubmitted(true);setAnswers(a=>[...a,{questionId:q.id,answer:draft,correct}])}
 function next(){if(index+1<active.length){setIndex(i=>i+1);setDraft('');setFeedback(null);setSubmitted(false)}else{const scored=answers;const a:Attempt={id:uid(),subjectId:selected,date:new Date().toLocaleString('ja-JP'),score:scored.filter(x=>x.correct).length,total:scored.filter(x=>x.correct!==null).length,answers:scored};setAttempts(v=>[a,...v].slice(0,100));setView('result')}}
 async function exportPdf(){if(!subject)return;const essay=attempts.find(a=>a.subjectId===subject.id)?.answers.filter(a=>subject.questions.find(q=>q.id===a.questionId)?.type==='essay')||[];if(!essay.length)return alert('出力できる論述答案がありません');const doc=new jsPDF();doc.setFontSize(16);doc.text(`${subject.name} - Essay Answers`,14,18);let y=30;essay.forEach((a,i)=>{const q=subject.questions.find(x=>x.id===a.questionId)!;const lines=[`Q${i+1}. ${q.question}`,`Answer: ${a.answer}`,`Model answer: ${q.modelAnswer||'-'}`,`Rubric: ${q.rubric||'-'}`];lines.forEach(line=>{doc.splitTextToSize(line,180).forEach((l:string)=>{if(y>280){doc.addPage();y=18}doc.text(l,14,y);y+=7})});y+=5});doc.save(`${subject.name}-essay-answers.pdf`)}
 if(!ready)return <main className="min-h-screen grid place-items-center">読み込み中…</main>;
 return <main className="min-h-screen"><header className="bg-[#17233f] text-white px-5 py-4"><div className="max-w-5xl mx-auto flex justify-between items-center"><button onClick={()=>setView('home')} className="font-black text-xl">Study Studio</button><span className="text-sm text-blue-200">試験対策ワークスペース</span></div></header><div className="max-w-5xl mx-auto p-4 md:p-8">
 {view==='home'&&<><div className="flex justify-between items-end mb-6"><div><h1 className="text-3xl font-black">科目</h1><p className="text-gray-500 mt-1">学習する科目を選んでください</p></div><button onClick={addSubject} className="bg-blue-600 text-white px-5 py-3 rounded-xl font-bold">＋ 科目を追加</button></div><div className="grid md:grid-cols-2 gap-4">{subjects.map(s=><button key={s.id} onClick={()=>openSubject(s)} className="card p-6 text-left hover:-translate-y-1 transition"><div className="flex justify-between"><h2 className="text-xl font-black">{s.name}</h2><span className="text-sm bg-blue-50 text-blue-700 px-3 py-1 rounded-full">{s.questions.length}問</span></div><p className="text-sm text-gray-500 mt-5">{s.source?s.source.mode==='sync'?'スプレッドシート同期':'スプレッドシートからコピー':'アプリ内で作成'}</p></button>)}</div>{!subjects.length&&<div className="card text-center p-14 text-gray-500">「科目を追加」から始めましょう</div>}</>}
 {view==='subject'&&subject&&<><button onClick={()=>setView('home')} className="text-gray-500 mb-5">← 科目一覧</button><div className="card p-6 md:p-8"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-black">{subject.name}</h1><p className="text-gray-500 mt-2">{subject.questions.length}問・挑戦{stats.length}回</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setSubjectSettings({...subject,source:subject.source?{...subject.source}:undefined,questions:[...subject.questions]})} className="border border-blue-300 text-blue-700 px-4 py-3 rounded-xl font-bold">科目設定</button><button onClick={deleteSubject} className="border border-red-300 text-red-600 px-4 py-3 rounded-xl font-bold">科目を削除</button><button onClick={()=>setView('manage')} className="border px-4 py-3 rounded-xl font-bold">問題管理</button><button onClick={start} className="bg-blue-600 text-white px-6 py-3 rounded-xl font-bold">学習開始</button></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-8">{(['choice','ox','fill','essay'] as QType[]).map(t=><div key={t} className="bg-gray-50 rounded-xl p-4"><p className="text-sm text-gray-500">{typeName[t]}</p><p className="text-2xl font-black mt-1">{subject.questions.filter(q=>q.type===t).length}</p></div>)}</div>{stats.length>0&&<div className="mt-8 border-t pt-6"><h2 className="font-black text-xl mb-3">最近の成績</h2>{stats.slice(0,5).map(a=><div key={a.id} className="flex justify-between py-3 border-b"><span>{a.date}</span><b>{a.score}/{a.total}</b></div>)}<button onClick={exportPdf} className="mt-5 border border-blue-600 text-blue-600 px-5 py-2 rounded-lg font-bold">最新の論述答案をPDF出力</button></div>}</div></>}
 {view==='manage'&&subject&&<><div className="flex justify-between mb-5"><button onClick={()=>setView('subject')}>← 科目へ</button><button onClick={()=>setEditing(blankQ())} className="bg-blue-600 text-white px-4 py-2 rounded-lg font-bold">＋ 問題作成</button></div><div className="space-y-3">{subject.questions.map(q=><div key={q.id} className="card p-4 flex justify-between gap-4"><div><span className="text-xs bg-gray-100 px-2 py-1 rounded">{typeName[q.type]}</span><p className="font-bold mt-2">{q.question}</p></div><div className="flex gap-2"><button onClick={()=>setEditing({...q})}>編集</button><button className="text-red-500" onClick={()=>confirm('削除しますか？')&&saveSubject({...subject,questions:subject.questions.filter(x=>x.id!==q.id)})}>削除</button></div></div>)}</div></>}
 {editing&&<div className="fixed inset-0 bg-black/40 p-4 grid place-items-center z-10"><div className="card p-6 w-full max-w-2xl max-h-[90vh] overflow-auto"><h2 className="text-xl font-black mb-4">問題を作成・編集</h2><label>形式<select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as QType})} className="block w-full border p-3 rounded-lg mt-1 mb-4">{Object.entries(typeName).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>問題文<textarea value={editing.question} onChange={e=>setEditing({...editing,question:e.target.value})} className="block w-full border p-3 rounded-lg mt-1 mb-4" rows={3}/></label>{editing.type==='choice'&&editing.options.map((o,i)=><input key={i} placeholder={`選択肢${i+1}`} value={o} onChange={e=>{const x=[...editing.options];x[i]=e.target.value;setEditing({...editing,options:x})}} className="block w-full border p-3 rounded-lg mb-2"/>)}{editing.type!=='essay'&&<label>正解<input value={editing.answer} onChange={e=>setEditing({...editing,answer:e.target.value})} placeholder={editing.type==='choice'?'正解の選択肢本文':editing.type==='ox'?'○ または ×':'穴埋めの正解'} className="block w-full border p-3 rounded-lg mt-1 mb-4"/></label>}<label>解説<textarea value={editing.explanation} onChange={e=>setEditing({...editing,explanation:e.target.value})} className="block w-full border p-3 rounded-lg mt-1 mb-4"/></label>{editing.type==='essay'&&<><label>模範解答<textarea value={editing.modelAnswer} onChange={e=>setEditing({...editing,modelAnswer:e.target.value})} className="block w-full border p-3 rounded-lg mt-1 mb-4" rows={4}/></label><label>採点ポイント<textarea value={editing.rubric} onChange={e=>setEditing({...editing,rubric:e.target.value})} className="block w-full border p-3 rounded-lg mt-1 mb-4" rows={3}/></label></>}<div className="flex justify-end gap-3"><button onClick={()=>setEditing(null)}>キャンセル</button><button onClick={saveQuestion} className="bg-blue-600 text-white px-5 py-2 rounded-lg font-bold">保存</button></div></div></div>}
 {pendingImport&&<div className="fixed inset-0 bg-black/40 p-4 grid place-items-center z-20"><div className="card p-6 w-full max-w-lg"><h2 className="text-xl font-black">読み込み方法を選択</h2><p className="text-gray-600 mt-2 mb-6">スプレッドシートの変更を自動反映するか、現在の問題を保存するか選んでください。</p><div className="grid gap-3"><button onClick={()=>finishImport('sync')} className="border-2 border-blue-600 bg-blue-50 text-blue-700 p-4 rounded-xl text-left"><b className="block text-lg">同期型</b><span className="text-sm">シートを更新すると、アプリにも反映されます</span></button><button onClick={()=>finishImport('copy')} className="border-2 border-gray-300 p-4 rounded-xl text-left"><b className="block text-lg">コピー型</b><span className="text-sm text-gray-600">登録時点の問題を端末内に保存します</span></button></div><button onClick={()=>setPendingImport(null)} className="w-full mt-5 text-gray-500">戻る</button></div></div>}
 {subjectSettings&&<div className="fixed inset-0 bg-black/40 p-4 grid place-items-center z-20"><div className="card p-6 w-full max-w-xl"><h2 className="text-xl font-black mb-5">科目設定</h2><label className="block font-bold">科目名<input value={subjectSettings.name} onChange={e=>setSubjectSettings({...subjectSettings,name:e.target.value})} className="block w-full border p-3 rounded-lg mt-2 mb-4 font-normal"/></label><label className="block font-bold">CSV URL<textarea value={subjectSettings.source?.url||''} onChange={e=>setSubjectSettings({...subjectSettings,source:e.target.value?{url:e.target.value,mode:subjectSettings.source?.mode||'sync'}:undefined})} placeholder="公開CSVのURLを貼り付け" rows={3} className="block w-full border p-3 rounded-lg mt-2 mb-4 font-normal"/></label><p className="font-bold mb-2">読み込み方式</p><div className="grid grid-cols-2 gap-3 mb-5"><button onClick={()=>setSubjectSettings({...subjectSettings,source:{url:subjectSettings.source?.url||'',mode:'sync'}})} className={`border-2 p-3 rounded-xl ${subjectSettings.source?.mode==='sync'?'border-blue-600 bg-blue-50 text-blue-700':'border-gray-200'}`}><b>同期型</b><span className="block text-xs mt-1">開くたび最新版を取得</span></button><button onClick={()=>setSubjectSettings({...subjectSettings,source:{url:subjectSettings.source?.url||'',mode:'copy'}})} className={`border-2 p-3 rounded-xl ${subjectSettings.source?.mode==='copy'?'border-blue-600 bg-blue-50 text-blue-700':'border-gray-200'}`}><b>コピー型</b><span className="block text-xs mt-1">読み込んだ問題を保存</span></button></div><button disabled={settingsLoading||!subjectSettings.source?.url} onClick={reloadSettings} className="w-full border border-blue-600 text-blue-700 disabled:border-gray-300 disabled:text-gray-400 py-3 rounded-xl font-bold">{settingsLoading?'読み込み中…':`今すぐ再読み込み（現在 ${subjectSettings.questions.length}問）`}</button><div className="flex justify-end gap-3 mt-6"><button disabled={settingsLoading} onClick={()=>setSubjectSettings(null)}>キャンセル</button><button disabled={settingsLoading} onClick={saveSettings} className="bg-blue-600 disabled:bg-gray-300 text-white px-5 py-2 rounded-lg font-bold">保存</button></div></div></div>}
 {view==='play'&&active[index]&&<div className="card p-6 md:p-10 max-w-3xl mx-auto"><div className="flex justify-between text-sm text-gray-500 mb-6"><span>{typeName[active[index].type]}</span><span>{index+1}/{active.length}</span></div><h1 className="text-xl md:text-2xl font-black leading-relaxed mb-7">{active[index].question}</h1>{active[index].type==='choice'?<div className="space-y-3">{active[index].options.map(o=><button key={o} disabled={submitted} onClick={()=>setDraft(o)} className={`w-full text-left border-2 p-4 rounded-xl ${draft===o?'border-blue-600 bg-blue-50':'border-gray-200'}`}>{o}</button>)}</div>:active[index].type==='ox'?<div className="grid grid-cols-2 gap-4">{['○','×'].map(o=><button key={o} disabled={submitted} onClick={()=>setDraft(o)} className={`text-4xl border-2 p-8 rounded-xl ${draft===o?'border-blue-600 bg-blue-50':''}`}>{o}</button>)}</div>:<textarea value={draft} disabled={submitted} onChange={e=>setDraft(e.target.value)} rows={active[index].type==='essay'?10:3} placeholder="回答を入力" className="w-full border-2 p-4 rounded-xl"/>}{submitted&&<div className="bg-gray-50 p-4 rounded-xl mt-5">{feedback!==null&&<b className={feedback?'text-green-600':'text-red-600'}>{feedback?'正解':'不正解'}</b>}<p className="mt-2">{active[index].explanation}</p>{active[index].type==='essay'&&<><p className="mt-3"><b>模範解答：</b>{active[index].modelAnswer}</p><p><b>採点ポイント：</b>{active[index].rubric}</p></>}</div>}<div className="flex justify-end mt-6">{!submitted?<button disabled={!draft.trim()} onClick={submit} className="bg-blue-600 disabled:bg-gray-300 text-white px-7 py-3 rounded-xl font-bold">回答する</button>:<button onClick={next} className="bg-blue-600 text-white px-7 py-3 rounded-xl font-bold">{index+1===active.length?'結果へ':'次へ'}</button>}</div></div>}
 {view==='result'&&subject&&<div className="card max-w-xl mx-auto text-center p-10"><h1 className="text-3xl font-black">学習完了</h1><p className="text-gray-500 mt-2">論述問題はPDFにまとめてAIで採点できます</p><div className="flex flex-col gap-3 mt-8"><button onClick={exportPdf} className="bg-blue-600 text-white py-3 rounded-xl font-bold">論述答案をPDF出力</button><button onClick={()=>setView('subject')} className="border py-3 rounded-xl font-bold">科目へ戻る</button></div></div>}
 </div></main>
}
